// Tokens.swift — draft generated by shared/gen-tokens.py. Values mirror tokens.json exactly.
// Dynamic colours resolve light/dark through UIColor/NSColor traits; dimensions are CGFloat points.
import SwiftUI

enum VVColor {
    private static func dynamic(_ light: Color, _ dark: Color) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { $0.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light) })
        #else
        return Color(NSColor(name: nil) { $0.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua ? NSColor(dark) : NSColor(light) })
        #endif
    }
    /// bg/canvas: light #FFFFFF, dark #08090A
    static let bgCanvas = dynamic(Color(red: 255/255, green: 255/255, blue: 255/255), Color(red: 8/255, green: 9/255, blue: 10/255))
    /// bg/raised: light #F6F7F9, dark #131415
    static let bgRaised = dynamic(Color(red: 246/255, green: 247/255, blue: 249/255), Color(red: 19/255, green: 20/255, blue: 21/255))
    /// bg/sunken: light #EDEEF0, dark #1C1D1E
    static let bgSunken = dynamic(Color(red: 237/255, green: 238/255, blue: 240/255), Color(red: 28/255, green: 29/255, blue: 30/255))
    /// bg/keyboard: light #E2E3E8, dark #222223
    static let bgKeyboard = dynamic(Color(red: 226/255, green: 227/255, blue: 232/255), Color(red: 34/255, green: 34/255, blue: 35/255))
    /// bg/inverse: light #111213, dark #F4F5F7
    static let bgInverse = dynamic(Color(red: 17/255, green: 18/255, blue: 19/255), Color(red: 244/255, green: 245/255, blue: 247/255))
    /// fg/primary: light #111213, dark #F4F5F7
    static let fgPrimary = dynamic(Color(red: 17/255, green: 18/255, blue: 19/255), Color(red: 244/255, green: 245/255, blue: 247/255))
    /// fg/secondary: light #5A5B5C, dark #9D9EA0
    static let fgSecondary = dynamic(Color(red: 90/255, green: 91/255, blue: 92/255), Color(red: 157/255, green: 158/255, blue: 160/255))
    /// fg/tertiary: light #737476, dark #7F8082
    static let fgTertiary = dynamic(Color(red: 115/255, green: 116/255, blue: 118/255), Color(red: 127/255, green: 128/255, blue: 130/255))
    /// fg/inverse: light #FFFFFF, dark #08090A
    static let fgInverse = dynamic(Color(red: 255/255, green: 255/255, blue: 255/255), Color(red: 8/255, green: 9/255, blue: 10/255))
    /// fg/key-label: light #050505, dark #FBFBFB
    static let fgKeyLabel = dynamic(Color(red: 5/255, green: 5/255, blue: 5/255), Color(red: 251/255, green: 251/255, blue: 251/255))
    /// line/hairline: light #E3E4E6, dark #262628
    static let lineHairline = dynamic(Color(red: 227/255, green: 228/255, blue: 230/255), Color(red: 38/255, green: 38/255, blue: 40/255))
    /// line/strong: light #BDBEC0, dark #474849
    static let lineStrong = dynamic(Color(red: 189/255, green: 190/255, blue: 192/255), Color(red: 71/255, green: 72/255, blue: 73/255))
    /// fill/key: light #FFFFFF, dark #464646
    static let fillKey = dynamic(Color(red: 255/255, green: 255/255, blue: 255/255), Color(red: 70/255, green: 70/255, blue: 70/255))
    /// fill/key-function: light #FFFFFF, dark #464646
    static let fillKeyFunction = dynamic(Color(red: 255/255, green: 255/255, blue: 255/255), Color(red: 70/255, green: 70/255, blue: 70/255))
    /// fill/key-pressed: light #E3E4E6, dark #474849
    static let fillKeyPressed = dynamic(Color(red: 227/255, green: 228/255, blue: 230/255), Color(red: 71/255, green: 72/255, blue: 73/255))
    /// fill/key-prominent: light #111213, dark #F4F5F7
    static let fillKeyProminent = dynamic(Color(red: 17/255, green: 18/255, blue: 19/255), Color(red: 244/255, green: 245/255, blue: 247/255))
    /// fill/control: light #EDEEF0, dark #262628
    static let fillControl = dynamic(Color(red: 237/255, green: 238/255, blue: 240/255), Color(red: 38/255, green: 38/255, blue: 40/255))
    /// fill/control-pressed: light #E3E4E6, dark #323334
    static let fillControlPressed = dynamic(Color(red: 227/255, green: 228/255, blue: 230/255), Color(red: 50/255, green: 51/255, blue: 52/255))
    /// state/recording: light #8A8D93 (mid grey), dark #E8766D (desaturated red).
    /// 2026-10-01: no red in light mode; then judged too strong, so both were
    /// softened.
    static let stateRecording = dynamic(Color(red: 138/255, green: 141/255, blue: 147/255), Color(red: 232/255, green: 118/255, blue: 109/255))
}

enum VVGray {
    static let g1 = VVColor_dynamic(Color(red: 255/255, green: 255/255, blue: 255/255), Color(red: 8/255, green: 9/255, blue: 10/255))
    static let g2 = VVColor_dynamic(Color(red: 246/255, green: 247/255, blue: 249/255), Color(red: 19/255, green: 20/255, blue: 21/255))
    static let g3 = VVColor_dynamic(Color(red: 237/255, green: 238/255, blue: 240/255), Color(red: 28/255, green: 29/255, blue: 30/255))
    static let g4 = VVColor_dynamic(Color(red: 227/255, green: 228/255, blue: 230/255), Color(red: 38/255, green: 38/255, blue: 40/255))
    static let g5 = VVColor_dynamic(Color(red: 214/255, green: 215/255, blue: 217/255), Color(red: 50/255, green: 51/255, blue: 52/255))
    static let g6 = VVColor_dynamic(Color(red: 189/255, green: 190/255, blue: 192/255), Color(red: 71/255, green: 72/255, blue: 73/255))
    static let g7 = VVColor_dynamic(Color(red: 151/255, green: 152/255, blue: 154/255), Color(red: 98/255, green: 99/255, blue: 101/255))
    static let g8 = VVColor_dynamic(Color(red: 115/255, green: 116/255, blue: 118/255), Color(red: 127/255, green: 128/255, blue: 130/255))
    static let g9 = VVColor_dynamic(Color(red: 90/255, green: 91/255, blue: 92/255), Color(red: 157/255, green: 158/255, blue: 160/255))
    static let g10 = VVColor_dynamic(Color(red: 65/255, green: 66/255, blue: 68/255), Color(red: 189/255, green: 190/255, blue: 192/255))
    static let g11 = VVColor_dynamic(Color(red: 38/255, green: 38/255, blue: 40/255), Color(red: 221/255, green: 222/255, blue: 224/255))
    static let g12 = VVColor_dynamic(Color(red: 17/255, green: 18/255, blue: 19/255), Color(red: 244/255, green: 245/255, blue: 247/255))
}

@inline(__always) private func VVColor_dynamic(_ l: Color, _ d: Color) -> Color {
    #if canImport(UIKit)
    return Color(UIColor { $0.userInterfaceStyle == .dark ? UIColor(d) : UIColor(l) })
    #else
    return Color(NSColor(name: nil) { $0.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua ? NSColor(d) : NSColor(l) })
    #endif
}

enum VVMetric {
    static let radiusXs: CGFloat = 4
    static let radiusKey: CGFloat = 7
    static let radiusTall: CGFloat = 10
    static let radiusCard: CGFloat = 14
    static let radiusSheet: CGFloat = 20
    static let radiusIsland: CGFloat = 44
    static let radiusPill: CGFloat = 999
    static let radiusCircle: CGFloat = 999
    static let space1: CGFloat = 4
    static let space2: CGFloat = 8
    static let space3: CGFloat = 12
    static let space4: CGFloat = 16
    static let space5: CGFloat = 20
    static let space6: CGFloat = 24
    static let space8: CGFloat = 32
    static let space10: CGFloat = 40
    static let space12: CGFloat = 48
    static let keyboardKeyHeight: CGFloat = 43
    static let keyboardRowGap: CGFloat = 11
    static let keyboardKeyGap: CGFloat = 6
    static let keyboardMarginX: CGFloat = 6
    static let keyboardStatusRowHeight: CGFloat = 44
    static let keyboardBottomInset: CGFloat = 8
    static let keyboardHomeArea: CGFloat = 34
    static let keyboardLabelSize: CGFloat = 23
    static let keyboardLabelSizeSmall: CGFloat = 16
    static let keyboardGlyphSize: CGFloat = 20
    static let micGlyph: CGFloat = 30
    static let micDiameterKeyboard: CGFloat = 112
    static let micSideDiameterKeyboard: CGFloat = 72
    static let micCapsuleHeightKeyboard: CGFloat = 112
    static let micDiameterBar: CGFloat = 56
    static let micSideDiameterBar: CGFloat = 56
    static let micCapsuleHeightBar: CGFloat = 56
    static let micHitColumns: CGFloat = 4
    static let micCapsuleColumns: CGFloat = 6
    static let micSideColumns: CGFloat = 2
    static let micAppBarHeight: CGFloat = 56
    static let waveformBarWidth: CGFloat = 2
    static let waveformBarPitch: CGFloat = 3
    static let waveformMinHeight: CGFloat = 2
    static let waveformAttackMs: CGFloat = 30
    static let waveformReleaseMs: CGFloat = 180
    static let waveformSampleHz: CGFloat = 15
    static let waveformDrawHz: CGFloat = 60
    static let waveformBarsKeyboard: CGFloat = 48
    static let waveformBarsMac: CGFloat = 14
    static let listRowMinHeight: CGFloat = 44
    static let listInset: CGFloat = 16
    static let listGap: CGFloat = 8
    static let listSectionGap: CGFloat = 24
    static let pillHeight: CGFloat = 28
    static let pillRadius: CGFloat = 14
    static let pillPaddingX: CGFloat = 12
    static let hairlineLightOpacity: CGFloat = 1
    static let hairlinePx: CGFloat = 1
    /// 1 physical pixel: 1/3 pt on @3x, 1/2 pt on @2x.
    static func hairline(_ scale: CGFloat) -> CGFloat { 1 / scale }
    /// Nested corner: inner radius = outer radius − inset, never below 0.
    static func nestedRadius(outer: CGFloat, inset: CGFloat) -> CGFloat { max(0, outer - inset) }
}

enum VVFont {
    /// 34/41 tracking 12/1000 em
    static let largeTitle = Font.system(size: 34, weight: .bold)
    static let largeTitleTracking: CGFloat = 0.41  // pt, for .tracking()
    static let largeTitleLineSpacing: CGFloat = 7  // approximate; verify with font metrics
    /// 28/34 tracking 14/1000 em
    static let title1 = Font.system(size: 28, weight: .bold)
    static let title1Tracking: CGFloat = 0.39  // pt, for .tracking()
    static let title1LineSpacing: CGFloat = 6  // approximate; verify with font metrics
    /// 22/28 tracking -12/1000 em
    static let title2 = Font.system(size: 22, weight: .bold)
    static let title2Tracking: CGFloat = -0.26  // pt, for .tracking()
    static let title2LineSpacing: CGFloat = 6  // approximate; verify with font metrics
    /// 20/25 tracking -23/1000 em
    static let title3 = Font.system(size: 20, weight: .semibold)
    static let title3Tracking: CGFloat = -0.46  // pt, for .tracking()
    static let title3LineSpacing: CGFloat = 5  // approximate; verify with font metrics
    /// 17/22 tracking -26/1000 em
    static let headline = Font.system(size: 17, weight: .semibold)
    static let headlineTracking: CGFloat = -0.44  // pt, for .tracking()
    static let headlineLineSpacing: CGFloat = 5  // approximate; verify with font metrics
    /// 17/22 tracking -26/1000 em
    static let body = Font.system(size: 17, weight: .regular)
    static let bodyTracking: CGFloat = -0.44  // pt, for .tracking()
    static let bodyLineSpacing: CGFloat = 5  // approximate; verify with font metrics
    /// 17/26 tracking -26/1000 em
    static let transcript = Font.system(size: 17, weight: .regular)
    static let transcriptTracking: CGFloat = -0.44  // pt, for .tracking()
    static let transcriptLineSpacing: CGFloat = 9  // approximate; verify with font metrics
    /// 16/21 tracking -20/1000 em
    static let callout = Font.system(size: 16, weight: .regular)
    static let calloutTracking: CGFloat = -0.32  // pt, for .tracking()
    static let calloutLineSpacing: CGFloat = 5  // approximate; verify with font metrics
    /// 15/20 tracking -16/1000 em
    static let subhead = Font.system(size: 15, weight: .regular)
    static let subheadTracking: CGFloat = -0.24  // pt, for .tracking()
    static let subheadLineSpacing: CGFloat = 5  // approximate; verify with font metrics
    /// 13/18 tracking -6/1000 em
    static let footnote = Font.system(size: 13, weight: .regular)
    static let footnoteTracking: CGFloat = -0.08  // pt, for .tracking()
    static let footnoteLineSpacing: CGFloat = 5  // approximate; verify with font metrics
    /// 12/16 tracking 0/1000 em
    static let caption1 = Font.system(size: 12, weight: .regular)
    static let caption1Tracking: CGFloat = 0.00  // pt, for .tracking()
    static let caption1LineSpacing: CGFloat = 4  // approximate; verify with font metrics
    /// 11/13 tracking 6/1000 em
    static let caption2 = Font.system(size: 11, weight: .regular)
    static let caption2Tracking: CGFloat = 0.07  // pt, for .tracking()
    static let caption2LineSpacing: CGFloat = 2  // approximate; verify with font metrics
    /// 22/28 tracking -12/1000 em
    static let timer = Font.system(size: 22, weight: .medium).monospacedDigit()
    static let timerTracking: CGFloat = -0.26  // pt, for .tracking()
    static let timerLineSpacing: CGFloat = 6  // approximate; verify with font metrics
    /// 44/52 tracking 8/1000 em
    static let timerLarge = Font.system(size: 44, weight: .medium).monospacedDigit()
    static let timerLargeTracking: CGFloat = 0.35  // pt, for .tracking()
    static let timerLargeLineSpacing: CGFloat = 8  // approximate; verify with font metrics
    /// 23/28 tracking -4/1000 em
    static let keyLabel = Font.system(size: 23, weight: .regular)
    static let keyLabelTracking: CGFloat = -0.09  // pt, for .tracking()
    static let keyLabelLineSpacing: CGFloat = 5  // approximate; verify with font metrics
}

enum VVMotion {
    /// Key press: no bounce, fast. Interruptible by construction (SwiftUI springs retarget).
    static let press = Animation.spring(duration: 0.18, bounce: 0)
    /// Key-to-panel morph (idle → listening and back).
    static let morph = Animation.spring(duration: 0.36, bounce: 0.12)
    /// Status row swaps, pills appearing.
    static let settle = Animation.spring(duration: 0.28, bounce: 0.05)
    /// Reduce Motion replacement for every spring above.
    static let reduced = Animation.easeOut(duration: 0.15)
    static let waveformAttack: Double = 0.030
    static let waveformRelease: Double = 0.180
}
